CREATE DATABASE data_analysis_project;

SELECT * FROM cleaned_data;

-- business insights questions

    -- 1. Which category generates highest revenue? 

SELECT 
    category,
    ROUND(SUM(purchase_amount), 2) AS highest_revenue
FROM cleaned_data
GROUP BY category
ORDER BY highest_revenue DESC;

-- ? Business 	Problem :- Company does not know which category contributes most to revenue

-- Impact :-
     -- Helps prioritize high-performing categories
     -- Optimizes inventory planning
     -- Improves marketing ROI
 
 -- 2. Are discounts actually increasing purchase value
SELECT discount_applied,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM cleaned_data
GROUP BY discount_applied;

-- ? Business Problem :- Discounts may reduce profit without increasing sales.
-- Impact :-
    -- Identify effectiveness of discounts
    -- Reduce unnecessary discount costs
    -- Improve profit margins

-- 3. What is the total revenue generated by male and female customer?
SELECT gender,
    ROUND(SUM(purchase_amount), 2) AS highest_revenue
FROM cleaned_data
GROUP BY gender
ORDER BY highest_revenue DESC;

-- ? Business Problem :- Lack of understanding of revenue contribution by gender segments.

-- Impact:-
     -- Helps design targeted marketing campaigns
     -- Improves customer segmentation strategy
     -- Enhances personalization efforts
     
-- 4. Which customer used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id,
    purchase_amount,
    discount_applied
FROM cleaned_data
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM cleaned_data)
LIMIT 10;

-- ? Business Problem:- Company cannot identify high-spending customers who are also discount users.

-- Impact :-
    -- Identify premium discount-specific customers
    -- Enabless targeted discount campaigns
    -- Improves customer retention and revenue

-- 5. Which are the top/bottom 5 products with the highest average rating.
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS Avg_ratings
 FROM cleaned_data
 GROUP BY item_purchased
 ORDER BY Avg_ratings DESC  -- Top 5
 LIMIT 5;
 
 SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS Avg_ratings
 FROM cleaned_data
 GROUP BY item_purchased
 ORDER BY Avg_ratings ASC  -- BOTTOM 5
 LIMIT 5;
 
 -- ? Business Problem:- No visibilty into product performance based on customer satisfaction.
 
 -- Impact:- 
      -- Promotes high_performing productss
      -- Improves low_rated products
      -- Enhances customer experience

-- 6. Average purchase standard vs express shipping
SELECT
    shipping_type,
    COUNT(DISTINCT customer_id) AS order_placed,
    ROUND(AVG(purchase_amount),2) AS avg_purchase,
    ROUND(SUM(purchase_amount),2) AS revenue
FROM cleaned_data
-- WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY revenue DESC;

-- ? Business Problem:- Unclear if faster shipping leads to higher spending

-- Impact:- 
     -- Helps optimize shipping pricing strategy
     -- Encourages premium shipping adoption
     -- Increase average order value
     
-- 7. Do subscribed customers spend more? Compare average spend and totall revenue between subscribers and non-subscribers.

SELECT 
     subscription_status,
     COUNT(customer_id) AS users,
     ROUND(AVG(purchase_amount),2) AS ang_revenue,
     ROUND(SUM(purchase_amount),2) AS total_revenue
FROM cleaned_data
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- ? Business Problem:- The effecctiveness of subscription progres is unknown

-- Impact
      -- Validates subscription model performance
      -- Improve customer loyalty progres
      -- Increases customer lifetime value 
      
-- 8. Top 5 products with highest discount usage %

SELECT 
    item_purchased,
    COUNT(item_purchased) AS total_number_of_times_sold,
    COUNT(CASE WHEN discount_applied= 'Yes' THEN 1 END) AS Number_of_time_sold_when_discount_applied,
    COUNT(CASE WHEN discount_applied= 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percent
FROM cleaned_data
GROUP BY item_purchased 
ORDER BY discount_percent DESC
LIMIT 5;

-- ? Business Problem:- Some products may be overly dependent on discounts.

-- Impact:-
    -- Identifies discount driven products
    -- Helps optimize pricing strategy
    -- Reduces profit margin loss
    
-- 9. Segment customer into new, returning and loyal based on their total number of previou purchase,
	-- and show the count of each segment.
    
SELECT 
    CASE
        WHEN previous_purchases = '0' THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count
FROM cleaned_data
GROUP BY CASE
          WHEN previous_purchases = '0' THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END;


-- ? Business Problem:- Lack of customer segmentation leads to generic strategies

-- Impact:-
       -- Enables personalised marketing
       -- Improves retention strategies
       -- Increase conversion rates

-- 10. What are the top 3 most purchased products within each category?

WITH CTE AS (
    SELECT 
        category,
        item_purchased,
        COUNT(item_purchased) AS most_purchased,
        RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
    FROM cleaned_data
    GROUP BY category, item_purchased -- Group by the specific columns
)
SELECT * FROM CTE
WHERE RNK < 3;

-- ? Business Problem:- The company doesn't know top_performing products within categories

-- Impact:-
      -- Improves product placement and redemption
      -- Helps inventory optimization
      -- Increases sales through best-sellers

-- 11. Are customers who are repeat buyers(more than 5 previous purchases) are likely to subscribe

SELECT
     CASE
         WHEN previous_purchases > 5 THEN 'Repeat Buyers'
         ELSE 'Normal Buyers'
     END AS customer_type,
     subscription_status,
     COUNT(*) AS customer_count,
     COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE
                                            WHEN previous_purchases > 5 THEN 'Repeat Buyers'
                                            ELSE 'Normal Buyers'
                                            END) AS percents
FROM cleaned_data
GROUP BY customer_type, subscription_status; -- Added subscription_status here

-- ? Business Problem :- Unclear relationship between loyalty and subscription.

-- Impact:-
       -- Improves subscription targeting
       -- Increases conversion to paid progress
       -- Increase customer retention strategy

-- 12. What is the revenue contribution of each age group?

SELECT
     CASE
         WHEN age BETWEEN 18 AND 25 THEN '18-25'
         WHEN age BETWEEN 26 AND 35 THEN '26-35'
         WHEN age BETWEEN 36 AND 50 THEN '36-50'
         ELSE '51+'
	 END AS age_group,
     ROUND(SUM(purchase_amount),2) AS total_revenue
FROM cleaned_data
GROUP BY CASE
         WHEN age BETWEEN 18 AND 25 THEN '18-25'
         WHEN age BETWEEN 26 AND 35 THEN '26-35'
         WHEN age BETWEEN 36 AND 50 THEN '36-50'
         ELSE '51+'
	END
    ORDER BY total_revenue DESC
    
    -- ? Business Problem:- No visibility into which age group contributes most to revvenue
    
    -- Impact:- 
         -- Enables age_based targeting
         -- Enhances marketing efficiency
